name = "FileUtils"
uuid = "3ab64cf3-766e-4aaa-abdf-a104b28521f5"
version = "0.1.10"
authors = ["Matthew Fishman <mfishman@flatironinstitute.org> and contributors"]

[workspace]
projects = ["benchmark", "dev", "docs", "examples", "test"]

[deps]
DeepDiffs = "ab62b9b5-e342-54a8-a765-a90f495de1a6"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"

[compat]
DeepDiffs = "1"
julia = "1.3"
